[package]
name = "AseraDB"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
sysinfo = "0.37.2"
colored = "2.0"
sqlparser = "0.60.0"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }